#!/usr/bin/env bash
# command to display all running process where
# A : Select all processes
# u : Select all processes on a terminal, including those of other users
# x : Select processes without controlling ttys 
echo ps -aux | less
