#!/usr/bin/env bash
# writess 'Best School' 10 times with while
i=1
while [ $i -ne 11 ]; do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
