#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but says "good luck" on 8th iteration and "bad luck" on 4th
letter="Best School"
x=1
while [ $x -ne 11 ];
do
        if [ $x -eq 4 ]
        then
        echo "bad luck"
        elif [ $x -eq 8 ]
        then
        echo "good luck"
        else
        echo "$letter"
        fi
        x=$(( x + 1 ))
done

