#!/usr/bin/env bash
# This script is displaying "Best School" 21 times but says "bad luck from China, Japan and Italy" on 4th, 9th and 17th
x=1
while [ $x -ne 21 ];
do
        echo "$x" 
        case "$x" in
                4) echo "bad luck from China";;
                9) echo "bad luck from Japan";;
                17) echo "bad luck from Italy";;
        esac
        x=$(( x + 1 ))
done

