#!/usr/bin/env bash
# Displays 12 hours and 59 minutes of the clock using while loop
hours=0
minutes=1
while [ $hours -ne 13 ]; do
    echo "Hour: $hours"
    while [ $minutes -ne 60 ]; do
        echo $minutes
        minutes=$((minutes + 1))
    done
    minutes=1
    hours=$((hours + 1))
done
